services:
  mysql:
    container_name: cinema-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinemadmin
      MYSQL_PASSWORD: pass4cinemadmin
  api:
    container_name: cinema-api
    build:
      context: .
      dockerfile: /buildImage/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql